using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace MvvmAIO.R3.SourceGenerators;

/// <summary>
/// Standard prefix for analyzer-emitted source files (CS8669 / RS1035 friendly).
/// </summary>
internal static class GeneratedSourceHeader
{
    public const string Prefix =
        """
        // <auto-generated/>
        #pragma warning disable
        #nullable enable

        """;

    public static string Apply(string source)
    {
        if (source.StartsWith("// <auto-generated/>", System.StringComparison.Ordinal))
        {
            return source;
        }

        return Prefix + source.TrimStart();
    }

    public static SyntaxTriviaList LeadingTrivia() =>
        TriviaList(
            Comment("// <auto-generated/>"),
            Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), true)),
            Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true)));
}
