using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using MvvmAIO.R3.SourceGenerators;
using Xunit;

namespace MvvmAIO.R3.SourceGenerators.Tests.Infrastructure;

internal static class CoreGeneratorScenarios
{
    internal const string FromEventsActionEventSource = """
        namespace Demo;

        public class ClickSource
        {
            public event System.Action? Click;
        }

        public static class Usage
        {
            public static void Run(ClickSource s) => s.FromEvents();
        }
        """;

    internal const string R3CommandVoidNoParameterSource = """
        namespace Demo;

        public partial class ShellViewModel
        {
            [MvvmAIO.R3.R3Command]
            private void Save()
            {
            }
        }
        """;

    internal const string R3CommandNonPartialSource = """
        namespace Demo;

        public class ShellViewModel
        {
            [MvvmAIO.R3.R3Command]
            private void Save()
            {
            }
        }
        """;

    internal static void AssertFromEventsActionEvent(GeneratorRunOutput output)
    {
        AssertNoErrors(output);
        string snapshot = GeneratorTestHarness.ToSnapshot(output);
        Assert.Contains("IClickSourceEvents", snapshot);
        Assert.Contains("Click", snapshot);
    }

    internal static void AssertR3CommandVoidNoParameter(GeneratorRunOutput output)
    {
        AssertNoErrors(output);
        string snapshot = GeneratorTestHarness.ToSnapshot(output);
        Assert.Contains("ReactiveCommand", snapshot);
        Assert.Contains("SaveCommand", snapshot);
        Assert.Contains("// <auto-generated/>", snapshot);
    }

    internal static void AssertR3CommandNonPartialDiagnostic(GeneratorRunOutput output)
    {
        string snapshot = GeneratorTestHarness.ToSnapshot(output);
        Assert.Contains("R3SG0001", snapshot);
        Assert.DoesNotContain("SaveCommand", snapshot);
    }

    private static void AssertNoErrors(GeneratorRunOutput output)
    {
        var errors = output.Diagnostics
            .Where(static d => d.Severity == DiagnosticSeverity.Error)
            .Where(static d => !d.Id.StartsWith("CS", StringComparison.Ordinal))
            .ToArray();
        Assert.True(errors.Length == 0, string.Join(System.Environment.NewLine, errors.Select(static e => e.ToString())));
    }
}
