// <auto-generated/> This file is overwritten by MSBuild.
namespace MvvmAIO.R3.SourceGenerators.Tests.Infrastructure;
internal static class RoslynTestConfig
{
public const string Flavor = "4120";
public const string CodeAnalysisVersion = "4.12.0";
public const string AnalyzerProject = "MvvmAIO.R3.SourceGenerators.Roslyn4120";
}
